<html>
<head><title></title>
</head>
<body>
<%
tclient = Request.Form("Tcliente")
rsocial = Request.Form("Rsocial")
nombre= Request.Form("Nombre")
rfc = Request.Form("RFC")
direc = Request.Form("Direc")
col = Request.Form("Col")
cp = Request.Form("CP")
deleg = Request.Form("Deleg")
edo = Request.Form("Edo")
tel = Request.Form("Tel")
tel2 = Request.Form("Tel2")
email = Request.Form("EMail")
continst = Request.Form("ContInst")
telcont = Request.Form("TelCont")
mismo = Request.Form("Mismo")
tclient = Request.Form("Tcliente2")
rsoc2 = Request.Form("Rsocial2")
nombre2 = Request.Form("Nombre2")
rfc = Request.Form("RFC2")
direc2 = Request.Form("Direc2")
col2 = Request.Form("Col2")
cp2 = Request.Form("CP2")
deleg2 = Request.Form("Deleg2")
edo2 = Request.Form("Edo2")
telef1 = Request.Form("Telef1")
telef2 = Request.Form("Telef2")
actv = Request.Form("Actv")
tserv = Request.Form("TipoServ")
marca = Request.Form("Marca")
modelo = Request.Form("Modelo")
tipo = Request.Form("Tipo")
anio = Request.Form("Anio")
placas = Request.Form("Placas")
color = Request.Form("Color")
motor = Request.Form("Motor")
noserie = Request.Form("NoSerie")
valvehi = Request.Form("Valor")
origen = Request.Form("Origen")
nomagen = Request.Form("NomAgen")
nomgerent = Request.Form("NomGernt")
nomvend = Request.Form("NomVendedor")
forma = Request.Form("Forma")
tiempo = Request.Form("Tiempo")
bancemisor = Request.Form("BancEmisor")
notarjta = Request.Form("NoTarjeta")
venc = Request.Form("Vencimiento")
codseg = Request.Form("CodSeg")
dominst = Request.Form("DomicInst")
domic = Request.Form("Domicilio")
obs = Request.Form("Obs")
%>
</body>
</html>